### ISSUE TITLE
Bidding ends with 1 club by opener

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#12]
When bidding interactively, after responder's pass, opener makes one last bid of one club.

**Comment by eddovandenboom** [comment]
![image](https://user-images.githubusercontent.com/62439033/92628943-da207880-f2cd-11ea-9552-5576f667b616.png)

A screenshot of the bug

**Comment by YkeSmit1** [comment]
Should be fixed by ending the auction after three passes
