### ISSUE TITLE
Relaying should stop at 6NT

### ISSUE THREAD

**Issue by YkeSmit1** [YkeSmit1/TOSR#29]
According to the TOSR document
"Denial cuebidding ends whenever any of the following three occurrences take place: b) The relayer bids 6nt or higher"
So opener has to pass if responder bids 6Sp or higher or place the contract

**Comment by YkeSmit1** [comment]
Fixed in commit 46d0f97a0a8cc770257c13fbeae406099854e614
If solver is not used, it can still go beyond 6NT, because it is needed to generate dictionaries
Also bidding always ends with 3 passes now

**Comment by eddovandenboom** [comment]
Bidding doesn't always end with 3 passes. For example, see issue #61
