### ISSUE TITLE
Interactive bidding doesn't work

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#32]
Two bugs in the interactive bidding that are probably related:
- The south bid is bid twice, causing an offset
- At the end of the shape phase, there is a NullReferenceException at the end of the method SouthBid: shape is null

**Comment by YkeSmit1** [comment]
Fixed in commit 95deccf208ac2f7096ca5c24085191eee147cc7d

**Comment by eddovandenboom** [comment]
Test successful
