### ISSUE TITLE
Show hand of opener in GUI after interactive bidding is finished

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#34]
I think it would be nice to be able to see the hand of opener/relayer after the interactive bidding is finished. Then you can analyze the bidding (system) better and also track bugs easier.

**Comment by YkeSmit1** [comment]
#fd1073081aac3482a6648a14b6913d4ebf79934c

**Comment by YkeSmit1** [comment]
fd1073081aac3482a6648a14b6913d4ebf79934c

**Comment by YkeSmit1** [comment]
Fixed in commit fd1073081aac3482a6648a14b6913d4ebf79934c
