### ISSUE TITLE
Last bid of interactive bidding is wrong

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#40]
When relayer bids final contract (for example 4♥) and you click pass as responder, you get the message "the correct bid is 4♥". Also sometimes the relayer bids 1♣ after final pass by responder.

**Comment by YkeSmit1** [comment]
passing of responder in interactive mode is correctly interpreted. And implemented option to bid again in interactive mode. Commit d71b99c72b594e50976c4c6746d679c16a4209b7

**Comment by eddovandenboom** [comment]
This issue doesn't have a corresponding unit test. We can consider adding one
