### ISSUE TITLE
Restrictions for responder's hand are not correct

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#41]
- Responder's hand can still contain less than 8HCP
- In interactive bidding responder's hand can have a distribution that cannot be bid (for example an 8card suit), resulting in an unhandled exception

**Comment by YkeSmit1** [comment]
Fixed in commit bb3f8e5f54c5807be5bae1099bd9d12a312f7872
I also added more validation to the ShuffleRestrictions form

**Comment by eddovandenboom** [comment]
The responder's hand can still contain less than 8 HCP. A shuffle restriction should be added
