### ISSUE TITLE
Store parameters for choosing relayer's bid in a file

### ISSUE THREAD

**Issue by YkeSmit1** [YkeSmit1/TOSR#44]
There should also be an option to use another parameter file in the UI.

**Comment by eddovandenboom** [comment]
Optimization parameters
- Percentage required to continue relaying for slam
- Number of hands to shuffle for sampling

Bidding system parameters
- Requirements to bid 3NT
- Requirements for relay bid
- Required max hcp to bid 4d

**Comment by eddovandenboom** [comment]
Loaded parameter file should also become a user setting
