### ISSUE TITLE
Add extra debug information about the auction

### ISSUE THREAD

**Issue by YkeSmit1** [YkeSmit1/TOSR#45]
The purpose is to investigate why an auction is wrong. Maybe this can be part of the description of the responder's bid. 
The following things should be stored: return values of solver, relay kind bid, interval, and parameters obtain from the responder's hand. Maybe some values can be stored in the logfile. It is also nice to store by how much off the end contract actually is. This can be in terms of a percentage.
Please test with the new branch ExperimnetalWayToGetNorthBid

**Comment by YkeSmit1** [comment]
implemented in commit 02a20225928e13ec25fef51c9905fbd6583be077

**Comment by eddovandenboom** [comment]
After I batch bid a set of hands, I have to select a filter first to see hands. I would find it more intuitive if the standard filter is "All" so that I see a hand immediately.

**Comment by eddovandenboom** [comment]
Test succeeded
