### ISSUE TITLE
"Go To Board" crashes program when empty pbn file is loaded

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#52]
After loading a PBN file, when entering a wrong value in the View-->Go To Board dialog, the program crashes.

**Comment by YkeSmit1** [comment]
Not sure what you mean. I was not able to reproduce it. Which wrong value do you mean?

**Comment by eddovandenboom** [comment]
The bug I found has a different cause than expected. When I load an empty file, and then try to go to a board number, the program crashes.

**Comment by eddovandenboom** [comment]
The program now displays the expected behaviour when an empty PBN file is loaded, but it still crashes when a file is loaded that doesn't have the correct format. I created a new issue for this: #62
