### ISSUE TITLE
Quantitative invite with minimal opening?

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#53]
The following hand, the opener bids a quantitative 4NT with no extra values and a misfit. I didn't look yet at why this happens, but it seems illogical to me.
![image](https://user-images.githubusercontent.com/62439033/104397024-287ba780-554c-11eb-8b56-f0d17c75214a.png)

**Comment by YkeSmit1** [comment]
It's different. It cannot pass because responder is unlimited. So it just bid the lowest NT bid, which happen to be 4NT

**Comment by eddovandenboom** [comment]
Ah okay, thank you for the explanation. I guess it is just a flaw in the bidding system then, because I don't think that 3NT should be unlimited (for example, responder can also bid 4NT instead of 3NT).
