### ISSUE TITLE
Add the ability to browse through the boards

### ISSUE THREAD

**Issue by YkeSmit1** [YkeSmit1/TOSR#54]
This should be possible after you have finished batchbidding or after you open a PBN file.
Also, in the title bar, it should specify PBN file and board number. 
It is maybe nice to have a navigator control
Also show the outcome in the status bar

**Comment by YkeSmit1** [comment]
Implemented in commit 75d4b73c58d938b3e837670046deaf10fb273aee

**Comment by eddovandenboom** [comment]
1. I expect the following behaviour:
When I enter a board number and press Enter, the program navigates to the correct board.
However, pressing the enter button has no result

2. Entering a negative value (or zero) as board number crashes the program

**Comment by eddovandenboom** [comment]
@YkeSmit1 I couldn't reproduce point 2. You can move this issue to "Done", unless you still want to work on the first point.
