### ISSUE TITLE
Bug in last part of interactive bidding

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#58]
![image](https://user-images.githubusercontent.com/62439033/105608084-7754e880-5d67-11eb-9857-effbd16c4aa0.png)
Something goes wrong here after the 6♠ bid.

**Comment by eddovandenboom** [comment]
![image](https://user-images.githubusercontent.com/62439033/105608644-c7cd4580-5d69-11eb-9e0e-e7c2f32b9715.png)
Another board with a similar bug (it might have the same cause).

**Comment by eddovandenboom** [comment]
![Uploading image.png…]()
Another possibly related bug

**Comment by YkeSmit1** [comment]
Calculate endcontract now takes into account if the endcontract is not a RelayBidKind
south now passes if no acceptable endcontract can be bid
End some small improvements
fix in commit d3965828b316b6c543abc7049ee37a94150e7583

**Comment by eddovandenboom** [comment]
Test OK, but see issue #61
