### ISSUE TITLE
Interactive bidding should store hand and auction in a PBN file

### ISSUE THREAD

**Issue by YkeSmit1** [YkeSmit1/TOSR#59]
After every successful interactive bidding or after clicking the butting "get auction",  it should save the board to the file "Interactive Bidding.pbn". This is mainly for debugging purposes. If you bid the board again, it should overwrite the previous board.

**Comment by YkeSmit1** [comment]
Fixed in commit 16f62d7e78c90274673903dbba839b1bbf3650e4

**Comment by eddovandenboom** [comment]
Test OK
