### ISSUE TITLE
Wrong final contract on 6 level

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#61]
Why doesn't declarer bid 6 hearts?
[interactive.zip](https://github.com/YkeSmit1/TOSR/files/5940569/interactive.zip)
![image](https://user-images.githubusercontent.com/62439033/107164268-f6efd380-6973-11eb-8888-8e2dfb8f6b4a.png)

**Comment by YkeSmit1** [comment]
This should be fixed by implementing the choose strategy change in the branch ExperimentalWayToGetNorthBid

**Comment by eddovandenboom** [comment]
Test succeeded
