### ISSUE TITLE
If >60% confidence cannot be reached, bid most reasonable contract instead of passing

### ISSUE THREAD

**Issue by eddovandenboom** [YkeSmit1/TOSR#67]
In the current program, a slam on finesse is not bid. Instead, the relayer passes, because the confidence in slam is less than the required 60%. I think that it is better to bid the contract with the highest confidence, regardless of whether it is less than or more than 60%.

**Comment by eddovandenboom** [comment]
Also, in Util.GetExpectedContract, the 60% is hard coded. Instead, there should be a reference to the optimization parameter requiredConfidenceToContinueRelaying.

**Comment by YkeSmit1** [comment]
Only implement parametrization of the 60%. The first issue is already

**Comment by YkeSmit1** [comment]
It is no longer an issue. EndContract is calculated in a different way. Util.GetExpectedContract is only used for checking if the contract is correct
